language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: "pip install -r requirements.txt"
script:
  - nosetests --verbose --detailed-errors --nocapture --with-id --with-coverage
  - exit 0
after_success:
  - coveralls
