language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: "pip install -r requirements.txt"
script:
  - export KERIO_USERNAME='admin-en'
  - export KERIO_PASSWORD='kerio'
  - nosetests --verbose --detailed-errors --nocapture --with-id --with-coverage tests/types/
  - nosetests --verbose --detailed-errors --nocapture --with-id --with-coverage tests/enums/
  - nosetests --verbose --detailed-errors --nocapture --with-id --with-coverage tests/structs/
  - nosetests --verbose --detailed-errors --nocapture --with-id --with-coverage tests/lists/
  - nosetests --verbose --detailed-errors --nocapture --with-id --with-coverage tests/interfaces/ || true
after_success:
  - coveralls
